
##
## The Hitchhiker's Guide to Python 
## https://learning.oreilly.com/library/view/the-hitchhikers-guide/9781491933213/
##


install-python3:
	brew install python3
	which python3

install-check:
	python3 --version
	python --version

install-pip3:
	## https://pip.pypa.io/en/stable/installing/
	curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
	python3 get-pip.py
	which pip3

install-virtualenv:
	pip3 install virtualenv
	which virtualenv

setup-virtualenv:
	cd my-project-folder
	virtualenv --python python3 my-venv
	source my-venv/bin/activate

setup-sublime-build:
	open https://medium.com/faun/sublime-text-3-and-python-3-build-on-macos-e76ab256422f




