all: clean

clean: 
	find . -name "*.class" -exec rm -rf {} \;

compile:
	javac *.java

run-hello-server:
	java GreetServer	

run-hello-client:
	java GreetClient

run-echo-server:
	java EchoServer	

run-echo-client:
	java EchoClient

run-echo-multiserver:
	java EchoMultiServer	

run-echo-clients:
	java EchoMultiClients

run-date-server:
	java DateServer

run-date-client:
	java DateClient

run-cap-server:
	java CapitalizeServer

run-cap-client:
	java CapitalizeClient

run-tic-tac-toe-server:
	java TicTacToeServer

run-tic-tac-toe-client:
	java TicTacToeClient

run-chat-server:
	java ChatServer

run-chat-client:
	java ChatClient


