all: clean

clean: 
	find . -name "*.class" -exec rm -rf {} \;

compile:
	javac *.java

run-server:
	java GreetServer	

run-client:
	java GreetClient

run-echo-server:
	java EchoServer	

run-echo-client:
	java EchoClient

run-echo-multiserver:
	java EchoMultiServer	

run-echo-clients:
	java EchoMultiClients

